In [1]:
import os
import pandas as pd
import time
import googlemaps 
from dotenv import load_dotenv

In [2]:
path= os.path.join("..",
    "data",
    "processed",
    "lagos_primary_health_centres_cleaned.xlsx"
)

df= pd.read_excel(path)
df.head()

,S/N,LGA/LCDA,WARD,ADDRESS,District,PHC_NAME
0,1,ALIMOSHO LGA,ALABATA,"100 AKOWONJO ROAD,VULGANIDER B/S",District 1,AKOWONJO PHC
1,2,ALIMOSHO LGA,OGUNTADE BAMEKE,"20,EJIGBO ROAD,ORISUNMIBARE, SHASHA",District 1,ORISUNBARE PHC
2,3,AGBADO OKE ODO LCDA,AGBADO OKEODO,"EKORO OKEODO ROAD, OKEODO ABULE EGBA",District 1,OKE ODO PHC
3,4,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL",District 1,SURULERE PHC.
4,5,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,"2/5, FADIPE STR, AGBADO",District 1,AMIKANLE PHC

In [3]:
df["google_address"] = None
df["place_id"] = None
df["lat"] = None
df["lon"] = None
df["geocode_method"] = None
df["status"] = None

In [4]:
df["query"] = (
    df["PHC_NAME"] + ", " +
    df["ADDRESS"] + ", " +
    df["LGA/LCDA"] + ", Lagos State, Nigeria"
)

In [5]:
df[["PHC_NAME", "query"]].head()

         PHC_NAME                                              query
0    AKOWONJO PHC  AKOWONJO PHC, 100 AKOWONJO ROAD,VULGANIDER B/S...
1  ORISUNBARE PHC  ORISUNBARE PHC, 20,EJIGBO ROAD,ORISUNMIBARE, S...
2     OKE ODO PHC  OKE ODO PHC, EKORO OKEODO ROAD, OKEODO ABULE E...
3   SURULERE PHC.  SURULERE PHC., 3, FAITH RESCUE BY COMMAND SECO...
4    AMIKANLE PHC  AMIKANLE PHC, 2/5, FADIPE STR, AGBADO, AGBADO ...

In [6]:
query = df.loc[0, "query"]

print(query)

AKOWONJO PHC, 100 AKOWONJO ROAD,VULGANIDER B/S, ALIMOSHO LGA, Lagos State, Nigeria

In [7]:
load_dotenv()

gmaps = googlemaps.Client(key=os.getenv("GOOGLE_API_KEY"))

result = gmaps.geocode(query)

result

[{'address_components': [{'long_name': '106',
    'short_name': '106',
    'types': ['street_number']},
   {'long_name': 'Akowonjo Road',
    'short_name': 'Akowonjo Rd',
    'types': ['route']},
   {'long_name': 'Alimosho',
    'short_name': 'Alimosho',
    'types': ['neighborhood', 'political']},
   {'long_name': 'Lagos',
    'short_name': 'Lagos',
    'types': ['locality', 'political']},
   {'long_name': 'Egbeda/Alimosho',
    'short_name': 'Egbeda/Alimosho',
    'types': ['administrative_area_level_3', 'political']},
   {'long_name': 'Alimosho',
    'short_name': 'Alimosho',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'Lagos',
    'short_name': 'LA',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'Nigeria',
    'short_name': 'NG',
    'types': ['country', 'political']},
   {'long_name': '102213', 'short_name': '102213', 'types': ['postal_code']}],
  'formatted_address': '106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria',
  'geometry': {'location': {'lat': 6.600395799999999, 'lng': 3.3003753},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 6.601696830291502,
     'lng': 3.301776630291501},
    'southwest': {'lat': 6.598998869708497, 'lng': 3.299078669708498}}},
  'navigation_points': [{'location': {'latitude': 6.6003348,
     'longitude': 3.3004272}}],
  'partial_match': True,
  'place_id': 'ChIJHxPHb62ROxARx4cTFuB_VPM',
  'plus_code': {'compound_code': 'J822+55 Lagos, Nigeria',
   'global_code': '6FR5J822+55'},
  'types': ['establishment', 'health', 'hospital', 'point_of_interest']},
 {'address_components': [{'long_name': '100',
    'short_name': '100',
    'types': ['street_number']},
   {'long_name': 'Akowonjo Road',
    'short_name': 'Akowonjo Rd',
    'types': ['route']},
   {'long_name': 'Alimosho',
    'short_name': 'Alimosho',
    'types': ['neighborhood', 'political']},
   {'long_name': 'Lagos',
    'short_name': 'Lagos',
    'types': ['locality', 'political']},
   {'long_name': 'Shasha/Akowonjo',
    'short_name': 'Shasha/Akowonjo',
    'types': ['administrative_area_level_3', 'political']},
   {'long_name': 'Alimosho',
    'short_name': 'Alimosho',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'Lagos',
    'short_name': 'LA',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'Nigeria',
    'short_name': 'NG',
    'types': ['country', 'political']},
   {'long_name': '102213', 'short_name': '102213', 'types': ['postal_code']}],
  'formatted_address': '100 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria',
  'geometry': {'location': {'lat': 6.599964399999999, 'lng': 3.299789},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 6.601291630291502,
     'lng': 3.301143230291502},
    'southwest': {'lat': 6.598593669708498, 'lng': 3.298445269708498}}},
  'navigation_points': [{'location': {'latitude': 6.5999737,
     'longitude': 3.2997888}}],
  'partial_match': True,
  'place_id': 'ChIJR-jqXa2ROxARbtAS7zyqdr8',
  'types': ['street_address', 'subpremise']},
 {'address_components': [{'long_name': 'B/S Lagos',
    'short_name': 'B/S Lagos',
    'types': ['premise']},
   {'long_name': '59', 'short_name': '59', 'types': ['street_number']},
   {'long_name': 'Okunola Road',
    'short_name': 'Okunola Rd',
    'types': ['landmark', 'route']},
   {'long_name': 'Okunola Street',
    'short_name': 'Okunola St',
    'types': ['route']},
   {'long_name': 'Abule Egba',
    'short_name': 'Abule Egba',
    'types': ['neighborhood', 'political']},
   {'long_name': 'Lagos',
    'short_name': 'Lagos',
    'types': ['locality', 'political']},
   {'long_name': 'Abule-Egba/Aboru/Meiran/Alagbado',
    'short_name': 'Abule-Egba/Aboru/Meiran/Alagbado',
    'types': ['administrative_area_level_3', 'political']},
   {'long_name': 'Alimosho',
    'short_name': 'Alimosho',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'Lagos',
    'short_name': 'LA',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'Nigeria',
    'short_name': 'NG',
    'types': ['country', 'political']},
   {'long_name': '102213', 'short_name': '102213', 'types': ['postal_code']}],
  'formatted_address': 'B/S Lagos, 59 Okunola St, off Okunola Road, Alimosho, Lagos 102213, Lagos, Nigeria',
  'geometry': {'bounds': {'northeast': {'lat': 6.6451479, 'lng': 3.2830645},
    'southwest': {'lat': 6.6450521, 'lng': 3.2829414}},
   'location': {'lat': 6.6451007, 'lng': 3.2830032},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 6.646457630291502,
     'lng': 3.284351930291502},
    'southwest': {'lat': 6.643759669708498, 'lng': 3.281653969708498}}},
  'navigation_points': [{'location': {'latitude': 6.6451132,
     'longitude': 3.2830118}}],
  'partial_match': True,
  'place_id': 'ChIJsblRKMmQOxARINjgOujIU9g',
  'types': ['premise', 'street_address']}]

In [8]:
location = result[0]

lat = location["geometry"]["location"]["lat"]
lon = location["geometry"]["location"]["lng"]

formatted_address = location["formatted_address"]

place_id = location["place_id"]

In [9]:
print(formatted_address)
print(lat)
print(lon)
print(place_id)

106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria
6.600395799999999
3.3003753
ChIJHxPHb62ROxARx4cTFuB_VPM

In [10]:
for place in result:
    print(place["types"])

['establishment', 'health', 'hospital', 'point_of_interest']
['street_address', 'subpremise']
['premise', 'street_address']

In [12]:
query = "AKOWONJO PHC, Alimosho, Lagos"

places = gmaps.places(query)

print(places)

{'html_attributions': [], 'results': [{'business_status': 'OPERATIONAL', 'formatted_address': '106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria', 'geometry': {'location': {'lat': 6.600395799999999, 'lng': 3.3003753}, 'viewport': {'northeast': {'lat': 6.601696830291502, 'lng': 3.301776630291502}, 'southwest': {'lat': 6.598998869708497, 'lng': 3.299078669708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/hospital-71.png', 'icon_background_color': '#F88181', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hospital-H_pinlet', 'name': 'Bola Tinubu Akowonjo Primary Health Centre', 'opening_hours': {'open_now': True}, 'photos': [{'height': 2252, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104368437225224486779">Ewaade 3A</a>'], 'photo_reference': 'AaVGc3nR0NrBnhZ1jt87FCFxMFXH0nlGXir_2j9DKnNqUwoLU7FGdlSw4wPVWw_9EXajbB-Pg4LO0cx6kipxXef9eiJq61ECZ3Ar7-CY2VOfPO7o_vVC5Ev-CFILKUIVjQaiz4AZStfJNvP_Tet1RHKBRUqH-7wCJbVrC7ZAzVZi7tDgr9uPBP4pi7NUJtDJKdytnYpLk8YZBEN0E9XiNF0wmzm1hfyPL9LfE3Kom1EIA4uinfGGCvHx-cIVE4vuJNbhUPxzE9AmuXKsURuKYpPmI7etWgwom_bFWap297EMbhjcvJws2uEl7wFBtLwHH3nhKbfSDWWbCDY9XQ-t7-_BjkDQu9-2qRbiGCpvOt7SqqJhgm1gM5pvzMTuycqaLIy426BezlupQImjrU2hvSoB03y9FsQ-_B-itzzkAD6U4gjYvvJ8', 'width': 4000}], 'place_id': 'ChIJHxPHb62ROxARx4cTFuB_VPM', 'plus_code': {'compound_code': 'J822+55 Lagos, Nigeria', 'global_code': '6FR5J822+55'}, 'rating': 4.4, 'reference': 'ChIJHxPHb62ROxARx4cTFuB_VPM', 'types': ['establishment', 'health', 'hospital', 'point_of_interest'], 'user_ratings_total': 21}, {'business_status': 'OPERATIONAL', 'formatted_address': 'J822+545, Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria', 'geometry': {'location': {'lat': 6.600387, 'lng': 3.3003667}, 'viewport': {'northeast': {'lat': 6.601696680291502, 'lng': 3.301775180291501}, 'southwest': {'lat': 6.598998719708497, 'lng': 3.299077219708498}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png', 'icon_background_color': '#7B9EB0', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet', 'name': 'Akowonjo Primary Healhcare Centre', 'opening_hours': {'open_now': True}, 'place_id': 'ChIJ1elGoMqROxARbJmb8F6LrKo', 'reference': 'ChIJ1elGoMqROxARbJmb8F6LrKo', 'types': ['establishment', 'health', 'point_of_interest']}], 'status': 'OK'}

In [13]:
places["results"][0]

{'business_status': 'OPERATIONAL',
 'formatted_address': '106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria',
 'geometry': {'location': {'lat': 6.600395799999999, 'lng': 3.3003753},
  'viewport': {'northeast': {'lat': 6.601696830291502,
    'lng': 3.301776630291502},
   'southwest': {'lat': 6.598998869708497, 'lng': 3.299078669708498}}},
 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/hospital-71.png',
 'icon_background_color': '#F88181',
 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hospital-H_pinlet',
 'name': 'Bola Tinubu Akowonjo Primary Health Centre',
 'opening_hours': {'open_now': True},
 'photos': [{'height': 2252,
   'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104368437225224486779">Ewaade 3A</a>'],
   'photo_reference': 'AaVGc3nR0NrBnhZ1jt87FCFxMFXH0nlGXir_2j9DKnNqUwoLU7FGdlSw4wPVWw_9EXajbB-Pg4LO0cx6kipxXef9eiJq61ECZ3Ar7-CY2VOfPO7o_vVC5Ev-CFILKUIVjQaiz4AZStfJNvP_Tet1RHKBRUqH-7wCJbVrC7ZAzVZi7tDgr9uPBP4pi7NUJtDJKdytnYpLk8YZBEN0E9XiNF0wmzm1hfyPL9LfE3Kom1EIA4uinfGGCvHx-cIVE4vuJNbhUPxzE9AmuXKsURuKYpPmI7etWgwom_bFWap297EMbhjcvJws2uEl7wFBtLwHH3nhKbfSDWWbCDY9XQ-t7-_BjkDQu9-2qRbiGCpvOt7SqqJhgm1gM5pvzMTuycqaLIy426BezlupQImjrU2hvSoB03y9FsQ-_B-itzzkAD6U4gjYvvJ8',
   'width': 4000}],
 'place_id': 'ChIJHxPHb62ROxARx4cTFuB_VPM',
 'plus_code': {'compound_code': 'J822+55 Lagos, Nigeria',
  'global_code': '6FR5J822+55'},
 'rating': 4.4,
 'reference': 'ChIJHxPHb62ROxARx4cTFuB_VPM',
 'types': ['establishment', 'health', 'hospital', 'point_of_interest'],
 'user_ratings_total': 21}

In [14]:
query = f"{df.loc[0, 'PHC_NAME']}, {df.loc[0, 'LGA/LCDA']}, Lagos"

places = gmaps.places(query)

In [15]:
query = (
    f"{df.loc[0, 'PHC_NAME']}, "
    f"{df.loc[0, 'ADDRESS']}, "
    f"{df.loc[0, 'LGA/LCDA']}, "
    "Lagos State, Nigeria"
)

geocode = gmaps.geocode(query)

In [16]:
query = "AKOWONJO PHC, ALIMOSHO LGA, Lagos State, Nigeria"

places = gmaps.places(query)

print(places["status"])

print(len(places["results"]))

result = places["results"][0]

print("Name:", result["name"])
print("Address:", result["formatted_address"])
print("Place ID:", result["place_id"])
print("Latitude:", result["geometry"]["location"]["lat"])
print("Longitude:", result["geometry"]["location"]["lng"])

OK
2
Name: Bola Tinubu Akowonjo Primary Health Centre
Address: 106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria
Place ID: ChIJHxPHb62ROxARx4cTFuB_VPM
Latitude: 6.600395799999999
Longitude: 3.3003753

In [17]:
new_columns = [
    "google_name",
    "google_address",
    "place_id",
    "lat",
    "lon",
    "geocode_method",
    "status",
    "partial_match"
]

for col in new_columns:
    if col not in df.columns:
        df[col] = None

In [18]:
df.columns

Index(['S/N', 'LGA/LCDA', 'WARD', 'ADDRESS', 'District', 'PHC_NAME',
       'google_address', 'place_id', 'lat', 'lon', 'geocode_method', 'status',
       'query', 'google_name', 'partial_match'],
      dtype='str')

In [19]:
#Create the Places function
# search_place() has one responsibility: search the Places API.


That separation makes the code easier to debug and extend.
def search_place(gmaps,phc_name, lga):
    """
    Search Google Places using the PHC name.
    """

    query = f"{phc_name}, {lga}, Lagos State, Nigeria"

    try:

        places = gmaps.places(query)

        if places["status"] == "OK" and places["results"]:

            result = places["results"][0]

            return {
                "status": "FOUND",
                "method": "Places",
                "google_name": result.get("name"),
                "google_address": result.get("formatted_address"),
                "place_id": result.get("place_id"),
                "lat": result["geometry"]["location"]["lat"],
                "lon": result["geometry"]["location"]["lng"],
                "partial_match": False
            }

    except Exception as e:

        print(e)

    return None

In [20]:
#Testing the function 
result = search_place(gmaps,
    "AKOWONJO PHC",
    "ALIMOSHO LGA"
)

result

{'status': 'FOUND',
 'method': 'Places',
 'google_name': 'Bola Tinubu Akowonjo Primary Health Centre',
 'google_address': '106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos, Nigeria',
 'place_id': 'ChIJHxPHb62ROxARx4cTFuB_VPM',
 'lat': 6.600395799999999,
 'lon': 3.3003753,
 'partial_match': False}

In [ ]:
#If that works,building the Geocoding fallback
#geocode_address() has one responsibility: geocode an address if Places didn't find anything.


def geocode_address(gmaps,phc_name, address, lga):
    """
    Fallback to Google Geocoding API.
    """

    query = (
        f"{phc_name}, "
        f"{address}, "
        f"{lga}, "
        "Lagos State, Nigeria"
    )

    try:

        results = gmaps.geocode(query)

        if results:

            result = results[0]

            return {
                "status": "FOUND",
                "method": "Geocoding",
                "google_name": None,
                "google_address": result.get("formatted_address"),
                "place_id": result.get("place_id"),
                "lat": result["geometry"]["location"]["lat"],
                "lon": result["geometry"]["location"]["lng"],
                "partial_match": result.get("partial_match", False)
            }

    except Exception as e:

        print(e)

    return None

In [21]:
# Building one master function ,This is where everything comes together.
# geocode_phc() orchestrates the workflow.

def geocode_phc(gmaps,row):

    # First attempt: Places
    result = search_place(gmaps,
        row["PHC_NAME"],
        row["LGA/LCDA"]
    )

    if result is not None:
        return result

    # Second attempt: Geocoding
    result = geocode_address(gmaps,
        row["PHC_NAME"],
        row["ADDRESS"],
        row["LGA/LCDA"]
    )

    if result is not None:
        return result

    # Failed
    return {
        "status": "FAILED",
        "method": None,
        "google_name": None,
        "google_address": None,
        "place_id": None,
        "lat": None,
        "lon": None,
        "partial_match": None
    }

In [23]:
result = geocode_phc(df.iloc[3])

result

{'status': 'FOUND',
 'method': 'Places',
 'google_name': 'Primary Healthcare Akerele',
 'google_address': '3 Akerele St, Akerele Extension, Lagos 101241, Lagos, Nigeria',
 'place_id': 'ChIJyVt6ZD6MOxARFLnPAsGPgt8',
 'lat': 6.5062156,
 'lon': 3.3526413,
 'partial_match': False}

In [ ]:
# Now we loop over the whole DataFrame 
for idx, row in df.iterrows():
    result = geocode_phc(row)

    for key, value in result.items():
        if key in df.columns:
            df.at[idx, key] = value

In [28]:
from pathlib import Path
import time
import pandas as pd

# Output folder
OUTPUT_DIR = Path("../data/processed")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

for idx, row in df.iterrows():

    # Skip rows that already have coordinates
    if pd.notna(row["lat"]) and pd.notna(row["lon"]):
        continue

    print(f"Processing {idx + 1}/{len(df)}: {row['PHC_NAME']}")

    result = geocode_phc(row)

    # Update dataframe with returned values
    for key, value in result.items():
        if key in df.columns:
            df.at[idx, key] = value

    # Save progress every 25 records
    if (idx + 1) % 25 == 0:
        df.to_excel(
            OUTPUT_DIR / "lagos_phc_geocoding_progress.xlsx",
            index=False
        )
        print(f"✅ Progress saved ({idx + 1} records)")

    # Avoid sending requests too quickly
    time.sleep(0.1)

# Final save
df.to_excel(
    OUTPUT_DIR / "lagos_phc_geocoded.xlsx",
    index=False
)

print("🎉 Geocoding complete! Final file saved.")

Processing 26/325: AILEGUN PHC
Processing 27/325: ONA IWAMIMO PHC
Processing 28/325: JAKANDE PHC
Processing 29/325: AIGBAKA PHC
Processing 30/325: IJEGUN PHC
Processing 31/325: IPINLERERE PHC
Processing 32/325: foundation PHC)
Processing 33/325: EGAN PHC
Processing 34/325: ODO ISUTI HEALTH POS
Processing 35/325: OKERUBE PHC
Processing 36/325: ISHERI-OSHUN PHC
Processing 37/325: AKINOGUN PHC
Processing 38/325: KOKUMO H/POST
Processing 39/325: AKINYELE PHC
Processing 40/325: RAUF AREGBESOLA PHC
Processing 41/325: AGBOJU PHC
Processing 42/325: IJEGUN PHC.
Processing 43/325: SATELLITE PHC
Processing 44/325: IBESHE PHC
Processing 45/325: KIRIKIRI PHC
Processing 46/325: IREDE HP.
Processing 47/325: POWERLINE PHC
Processing 48/325: SORETIRE PHC
Processing 49/325: ODUNMBAKU PHC
Processing 50/325: PAPA ASHAFA H/POST
✅ Progress saved (50 records)
Processing 51/325: SANGO PHC
Processing 52/325: ILORO PHC
Processing 53/325: DOPEMU PHC
Processing 54/325: KWAKWA UKU PHC
Processing 55/325: AJEGUNLE H/POST
Processing 56/325: AINA AJOBO PHC
Processing 57/325: IFAKO PHC
Processing 58/325: IJU PHC
Processing 59/325: OBAWOLE PHC
Processing 60/325: OGUNDIMU PHC
Processing 61/325: AGBADO/KOLA PHC
Processing 62/325: ABULE TITUN PHC
Processing 63/325: ILO AJEGUNLE PHC
Processing 64/325: ISOKAN PHC
Processing 65/325: ADESOLA PHC
Processing 66/325: OJOKORO PHC
Processing 67/325: IGBOGBO PHC
Processing 68/325: BAYEKU PHC
Processing 69/325: LAJO H/POST
Processing 70/325: OFFIN HEALTH POST
Processing 71/325: EWU ELEPE PHC
Processing 72/325: IBESHE PHC
Processing 73/325: MOJODA PHC
Processing 74/325: IJEDE PHC
Processing 75/325: OKE ELETU PHC
✅ Progress saved (75 records)
Processing 76/325: ABULE EKO PHC
Processing 77/325: IKORODU/ITA ELEWA PHC
Processing 78/325: EMMANUEL OSHINOWO CHILDREN CENTRE
Processing 79/325: AGURA PHC
Processing 80/325: AGBELE PHC
Processing 81/325: AGBEDE PHC
Processing 82/325: LOSI OBA PHC
Processing 83/325: ODO NLA PHC
Processing 84/325: OMOLAIYE HP
Processing 85/325: OLORUNDA PHC
Processing 86/325: ISIU PHC
Processing 87/325: PARAFA PHC
Processing 88/325: ERUWEN HP
Processing 89/325: LASUNWON PHC
Processing 90/325: MAJIDUN PHC
Processing 91/325: IPAKODO PHC
Processing 92/325: IGBO OLOMU PHC
Processing 93/325: ORI OKUTA PHC
Processing 94/325: MENDE PHC
Processing 95/325: OGUDU PHC
Processing 96/325: OWORO PHC
Processing 97/325: IKOSI PHC
Processing 98/325: ISHERI PHC
Processing 99/325: OLOWORA PHC (FORMER IKOSI ISHERI MUTUAL PLAN)
Processing 100/325: MAIDAN PHC
✅ Progress saved (100 records)
Processing 101/325: IDERA HP
Processing 102/325: AGBOYI PHC
Processing 103/325: AJEGUNLE PHC
Processing 104/325: ALAPERE PHC
Processing 105/325: KETU (MASCARA) PHC
Processing 106/325: ASHOGBON PHC
Processing 107/325: MAFOWOKU PHC
Processing 108/325: C.M.S PHC
Processing 109/325: EVA ADELAJA PHC
Processing 110/325: AKOKA PHC
Processing 111/325: BAJULAIYE PHC
Processing 112/325: OHEKENU PHC
Processing 113/325: WRIGHT PHC
Processing 114/325: DR IBIJOKE SANWO-OLU PHC
Processing 115/325: AKINWUNMI AMBODE PHC
Processing 116/325: IMOTA PHC
Processing 117/325: IGBALU/IGBOKUTA PHC
Processing 118/325: ORI OKUTA PHC
Processing 119/325: EPE PHC
Processing 120/325: AFUYE PHC
Processing 121/325: PAPA PHC
Processing 122/325: EREPOTO HEALTH POST
Processing 123/325: SAGIDAN PHC
Processing 124/325: ODOMOLA PHC
Processing 125/325: IGBONLA PHC
✅ Progress saved (125 records)
Processing 126/325: ILARA PHC
Processing 127/325: EREDO PHC
Processing 128/325: MOJODA PHC
Processing 129/325: IBOWON PHC
Processing 130/325: AGBOWA PHC
Processing 131/325: ADO IKOSI BEACH PHC
Processing 132/325: OTTA IKOSI PHC
Processing 133/325: OWU PHC
Processing 134/325: ODO AYANDELU PHC
Processing 135/325: EJINRIN PHC
Processing 136/325: ORUGBO PHC
Processing 137/325: ITOIKIN PHC
Processing 138/325: IGBODU HP
Processing 139/325: IBEJU PHC
Processing 140/325: AYETEJU PHC
Processing 141/325: AWOYAYA PHC 1
Processing 142/325: AWOYAYA PHC 2 (CBHIS)
Processing 143/325: LAKOWE PHC
Processing 144/325: OTUNLA PHC
Processing 145/325: BOGIJE PHC
Processing 146/325: SOLU-ALADE PHC
Processing 147/325: DEBOJO PHC
Processing 148/325: IBEREKODO PHC
Processing 149/325: ORIMEDU PHC
Processing 150/325: OKUN ISE PHC
✅ Progress saved (150 records)
Processing 151/325: ISE PHC
Processing 152/325: ABOREJI PHC
Processing 153/325: MAGBON-SEGUN PHC
Processing 154/325: IDASHO PHC
Processing 155/325: IDOTUN PHC
Processing 156/325: OKUNRAYE PHC
Processing 157/325: OSOROKO PHC
Processing 158/325: LEKKI PHC
Processing 159/325: APAKIN PHC
Processing 160/325: FOLU PHC
Processing 161/325: IGBO-OLOMI PHC
Processing 162/325: IDEH PHC
Processing 163/325: ADDO PHC
Processing 164/325: AJAH PHC
Processing 165/325: BADORE PHC
Processing 166/325: SANGOTEDO PHC
Processing 167/325: OKUNMOPO PHC
Processing 168/325: IFESOWAPO PHC FORMERLY ARAROMI PHC
Processing 169/325: OGOMBO HP
Processing 170/325: IGBOEFON PHC
Processing 171/325: GBARA MAIYEGUN HP
Processing 172/325: IKOTA PHC
Processing 173/325: IKATE PHC
Processing 174/325: AJIRAN HP
Processing 175/325: S.A AYEYEMI PHC-ILASAN
✅ Progress saved (175 records)
Processing 176/325: OBALENDE PHC
Processing 177/325: IKOYI PHC
Processing 178/325: ORIYANRIN PHC
Processing 179/325: TARKWABAY HP
Processing 180/325: ONIRU PHC
Processing 181/325: IPONRI PHC
Processing 182/325: AKERELE PHC
Processing 183/325: COKER/AGUDA PHC
Processing 184/325: ORILE IGANMU PHC
Processing 185/325: BARUWA PHC
Processing 186/325: EJIRE PHC
Processing 187/325: AIRWAYS PHC
Processing 188/325: ANJORIN PHC
Processing 189/325: FEMI GBAJABIAMILA PHC
Processing 190/325: SIMPSON PHC
Processing 191/325: ABULE NLA PHC
Processing 192/325: ONDO ST WEST PHC
Processing 193/325: OTUMARA PHC
Processing 194/325: OTTO PHC
Processing 195/325: IWAYA PHC
Processing 196/325: OBA SALAMI PHC
Processing 197/325: ALLI DAODU PHC
Processing 198/325: ALHAJI KOLA OSHO PHC
Processing 199/325: AIYETORO PHC
Processing 200/325: IJORA OLOYE PHC
✅ Progress saved (200 records)
Processing 201/325: OLUWOLE PHC
Processing 202/325: NANTI PHC
Processing 203/325: OLOJOWON PHC
Processing 204/325: SARI PHC
Processing 205/325: OJORA OLUGBODE PHC
Processing 206/325: ZION PHC
Processing 207/325: MARINE BEACH HEALTH POST
Processing 208/325: OLOWOGBOWO PHC
Processing 209/325: TAJUDEEN OLUSI HP
Processing 210/325: OBA ADEYINKA OYEKAN PHC
Processing 211/325: AGARAWU PHC
Processing 212/325: OKO AWO YOUTH FRIENDLY CENTRE
Processing 213/325: OKE ARIN HP
Processing 214/325: ONOLA HP
Processing 215/325: ITA-FAJI HP
Processing 216/325: FEMI PEDRO HEALTH CENTRE
Processing 217/325: PHASE 3 PHC
Processing 218/325: CITY HALL HP (CARENA)
Processing 219/325: IBIJOKE SANWOLU PHC (FORMER ANIKANTAMO HP)
Processing 220/325: ARAROMI PHC
Processing 221/325: SEME PHC
Processing 222/325: SAKPO PHC
Processing 223/325: APA PHC
Processing 224/325: IGBOGBELE PHC
Processing 225/325: FARASIME PHC
✅ Progress saved (225 records)
Processing 226/325: AJARA PHC
Processing 227/325: GBEREFU PHC
Processing 228/325: MARINA PHC
Processing 229/325: WILBROS PHC
Processing 230/325: AJIDO PHC
Processing 231/325: POTA PHC
Processing 232/325: IRAGBO/IRAGAN PHC
Processing 233/325: TOPO/IDALE PHC
Processing 234/325: TOPA HP
Processing 235/325: ILADO PHC
Processing 236/325: OBELE ESEPE PHC
Processing 237/325: ROTARY MEDICAL PORTACABIN PHC
Processing 238/325: IBEREKO PHC
Processing 239/325: ARAROMI PHC
Processing 240/325: MOROGBO PHC
Processing 241/325: ILOGBO PHC
Processing 242/325: ISAMOLE PHC
Processing 243/325: MOWO PHC
Processing 244/325: ERA PHC
Processing 245/325: IJANIKIN PHC
Processing 246/325: SHIBIRI PHC
Processing 247/325: OKE IJEUN PHC
Processing 248/325: ISHAGIRA PHC
Processing 249/325: IMUDE PHC
Processing 250/325: OJO PHC
✅ Progress saved (250 records)
Processing 251/325: IGBEDE PHC
Processing 252/325: IREWE PHC
Processing 253/325: IRA HEALTH POST
Processing 254/325: TEDI PHC
Processing 255/325: IJAGEMO PHC
Processing 256/325: IBA PHC
Processing 257/325: IJEDODO PHC
Processing 258/325: AFROMEDIA PHC
Processing 259/325: ISHASI PHC
Processing 260/325: OKOKOMAIKO PHC
Processing 261/325: KEMBERI PHC
Processing 262/325: FESTAC PHC
Processing 263/325: MILE 2 PHC
Processing 264/325: SAGBOKOJI PHC
Processing 265/325: TOMARO HEALTH POST
Processing 266/325: IGBOLOGUN PHC
Processing 267/325: BOLA AHMED TINUBU PHC (FORMERLY ADOSOBA PHC)
Processing 268/325: AKERE PHC
Processing 269/325: IBAFON PHC
Processing 270/325: TOLU PHC
Processing 271/325: AJEGUNLE PHC
Processing 272/325: LAYENI PHC
Processing 273/325: ORIDILU HP
Processing 274/325: AMUKOKO PHC
Processing 275/325: AGBOJU PHC
✅ Progress saved (275 records)
Processing 276/325: IJEGUN PHC.
Processing 277/325: SATELLITE PHC
Processing 278/325: IBESHE PHC
Processing 279/325: KIRIKIRI PHC
Processing 280/325: IREDE HP.
Processing 281/325: ALAUSA PHC
Processing 282/325: IKEJA PHC
Processing 283/325: ONILEKERE PHC
Processing 284/325: ONIPETESI HP
Processing 285/325: ADENIYI JONES PHC
Processing 286/325: Bola Ahmed Tinubu PHC (FORMER ALADE PHC)
Processing 287/325: Oregun PHC
Processing 288/325: Onigbongbo PHC
Processing 289/325: Beko Ransome-Kuti PHC
Processing 290/325: Wasimi PHC
Processing 291/325: OLUSOSUN PHC.
Processing 292/325: ABULE ONIGBAGBO PHC (FORMER OPEBI PHC)
Processing 293/325: OPEBI PHC
Processing 294/325: OJODU PHC
Processing 295/325: OGBA PHC
Processing 296/325: OKE IRA POWERLINE PHC
Processing 297/325: AKIODE PHC
Processing 298/325: AGIDINGBI PHC
Processing 299/325: OKE IRA CENTRAL PHC
Processing 300/325: AGUDA PHC
✅ Progress saved (300 records)
Processing 301/325: PALM AVENUE PHC
Processing 302/325: ISOLO RAOD PHC
Processing 303/325: IGBO OWU PHC
Processing 304/325: AJEABO PHC
Processing 305/325: ALVES PHC
Processing 306/325: IDI ARABA H/POST
Processing 307/325: ITIRE/IJESHA PHC
Processing 308/325: KAJOLA PHC
Processing 309/325: AYANTUGA PHC
Processing 310/325: ANIKULAPO PHC
Processing 311/325: COKER PHC
Processing 312/325: AJISEGIRI PHC
Processing 313/325: OSHODI PHC
Processing 314/325: EWUTUNTUN PHC
Processing 315/325: SHOGUNLE PHC
Processing 316/325: AYO NI PHC
Processing 317/325: MAFOLUKU PHC
Processing 318/325: OGUNOLOKO PHC
Processing 319/325: ISHAGA PHC
Processing 320/325: ILASA PHC
Processing 321/325: ISOLO PHC
Processing 322/325: OKOTA PHC
Processing 323/325: LSDPC PHC
Processing 324/325: APENA PHC
Processing 325/325: AJAO PHC
✅ Progress saved (325 records)
🎉 Geocoding complete! Final file saved.

In [29]:
df["status"].value_counts()

status
FOUND    325
Name: count, dtype: int64

In [30]:
df["geocode_method"].value_counts()

Series([], Name: count, dtype: int64)

In [31]:
failed = df[df["status"] == "FAILED"]

failed[["PHC_NAME", "ADDRESS", "LGA/LCDA"]]

Empty DataFrame
Columns: [PHC_NAME, ADDRESS, LGA/LCDA]
Index: []

In [32]:
df[df["partial_match"] == True][
    [
        "PHC_NAME",
        "ADDRESS",
        "google_address"
    ]
]

Empty DataFrame
Columns: [PHC_NAME, ADDRESS, google_address]
Index: []

In [33]:
df.head()

,S/N,LGA/LCDA,WARD,ADDRESS,District,PHC_NAME,google_address,place_id,lat,lon,geocode_method,status,query,google_name,partial_match
0,1,ALIMOSHO LGA,ALABATA,"100 AKOWONJO ROAD,VULGANIDER B/S",District 1,AKOWONJO PHC,"106 Akowonjo Rd, Alimosho, Lagos 102213, Lagos...",ChIJHxPHb62ROxARx4cTFuB_VPM,6.600396,3.300375,None,FOUND,"AKOWONJO PHC, 100 AKOWONJO ROAD,VULGANIDER B/S...",Bola Tinubu Akowonjo Primary Health Centre,False
1,2,ALIMOSHO LGA,OGUNTADE BAMEKE,"20,EJIGBO ROAD,ORISUNMIBARE, SHASHA",District 1,ORISUNBARE PHC,"Orisunbare Rd, Isheri Olofin, Ikeja 102214, La...",ChIJCYqMIHGROxARq7n7xxRZmrw,6.57007,3.302892,None,FOUND,"ORISUNBARE PHC, 20,EJIGBO ROAD,ORISUNMIBARE, S...",Orisunbare Primary Health Care Centre,False
2,3,AGBADO OKE ODO LCDA,AGBADO OKEODO,"EKORO OKEODO ROAD, OKEODO ABULE EGBA",District 1,OKE ODO PHC,"J7QW+RFG, Old Otta Rd, Oke Odo, Lagos 102213, ...",ChIJTVGehnaROxARtrDYIEsQ5m8,6.639574,3.29621,None,FOUND,"OKE ODO PHC, EKORO OKEODO ROAD, OKEODO ABULE E...",Oke-Odo Primary Healthcare Centre,False
3,4,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,"3, FAITH RESCUE BY COMMAND SECONDARY SCHOOL",District 1,SURULERE PHC.,"3 Akerele St, Akerele Extension, Lagos 101241,...",ChIJyVt6ZD6MOxARFLnPAsGPgt8,6.506216,3.352641,None,FOUND,"SURULERE PHC., 3, FAITH RESCUE BY COMMAND SECO...",Primary Healthcare Akerele,False
4,5,AGBADO OKE ODO LCDA,AJASA/AMIKANLE,"2/5, FADIPE STR, AGBADO",District 1,AMIKANLE PHC,"12 Peter Odeyale St, Oke Odo, Lagos 102213, La...",ChIJEXRPsleROxARMAQg-XIcxas,6.638108,3.284097,None,FOUND,"AMIKANLE PHC, 2/5, FADIPE STR, AGBADO, AGBADO ...",AGBELEKALE PRIMARY HEALTH CARE CENTRE,False

load_dotenv()

gmaps = googlemaps.Client(key=os.getenv("GOOGLE_API_KEY"))



for i in range(len(df)):
    address = (
    f"{df.loc[i, 'PHC_NAME']}, "
    f"{df.loc[i, 'ADDRESS']}, "
    f"Lagos State, Nigeria"
)

    try:
        result = gmaps.geocode(address)

        if result:
            df.loc[i, "lat"] = result[0]["geometry"]["location"]["lat"]
            df.loc[i, "lon"] = result[0]["geometry"]["location"]["lng"]

    except Exception as e:
        print(f"Row {i}: {e}")

    if (i + 1) % 25 == 0:
        df.to_excel("data/processed/geocoding_progress.xlsx", index=False)
        print(f"Saved progress at row {i + 1}")

    time.sleep(0.1)